name: 'Styleguide Bot'
description:
  'PRの変更内容をStyleguideに基づいてチェックし、違反がある場合はコメントを返すGitHub
  Action'
author: 'Ko Yamaura'

# ブランディングの設定
branding:
  icon: 'check-circle'
  color: 'blue'

# 入力パラメータの定義
inputs:
  styleguide:
    description:
      'StyleGuideのURL（例: https://google.github.io/styleguide/jsguide.html）'
    required: true
  openai-api-key:
    description: 'OpenAI APIキー（ChatGPTを使用するために必要）'
    required: true
  github-token:
    description: 'GitHub Token（PRへのコメント投稿に使用）'
    required: true
    default: ${{ github.token }}

# アクションの実行設定
runs:
  using: 'node20'
  main: 'dist/index.js'
